/* Generated Code (IMPORT) */
/* Source File: Sample_Class_Assessment_Grades.xlsx */
/* Source Path: /home/u63794575/Practice */
/* Code generated on: 3/27/24, 9:16 AM */

%web_drop_table(WORK.GRADES);


FILENAME REFFILE '/home/u63794575/Practice/Sample_Class_Assessment_Grades.xlsx';

PROC IMPORT DATAFILE=REFFILE
	DBMS=XLSX
	OUT=WORK.GRADES;
	GETNAMES=YES;
RUN;

PROC CONTENTS DATA=WORK.GRADES; RUN;


%web_open_table(WORK.GRADES);

/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '3/27/24, 9:18 AM' 
 * Generated by 'u63794575' 
 * Generated on server 'ODAWS01-USW2-2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.12.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2-2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-04%253A00&ticket=ST-251599-OiV9SDQEH2WnQqq0vYG1-cas' 
 *
 */

ods noproctitle;

/*** Analyze categorical variables ***/
title "Frequencies for Categorical Variables";

proc freq data=WORK.GRADES;
	tables assessment_form / plots=(freqplot);
run;

/*** Analyze numeric variables ***/
title "Descriptive Statistics for Numeric Variables";

proc means data=WORK.GRADES n nmiss min mean median max std;
	var standard1_score standard2_score standard3_score standard4_score grade;
run;

title;

proc univariate data=WORK.GRADES noprint;
	histogram standard1_score standard2_score standard3_score standard4_score 
		grade;
run;

/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '3/27/24, 9:22 AM' 
 * Generated by 'u63794575' 
 * Generated on server 'ODAWS01-USW2-2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.12.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M7P08062020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2-2.oda.sas.com/SASStudio/main?locale=en_US&zone=GMT-04%253A00&ticket=ST-251599-OiV9SDQEH2WnQqq0vYG1-cas' 
 *
 */

ods graphics / reset width=6.4in height=4.8in imagemap;

proc sgplot data=WORK.GRADES;
	vbox standard1_score /;
	yaxis grid;
run;

proc sgplot data=WORK.GRADES;
	vbox standard2_score /;
	yaxis grid;
run;

proc sgplot data=WORK.GRADES;
	vbox standard3_score /;
	yaxis grid;
run;

proc sgplot data=WORK.GRADES;
	vbox standard4_score /;
	yaxis grid;
run;

proc sgplot data=WORK.GRADES;
	vbox grade /;
	yaxis grid;
run;

ods graphics / reset;

